// versiculo.js – Biblioteca Epignósis

const versiculos = [
  "A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos. (Hebreus 11:1)",
  "O Senhor é o meu pastor, nada me faltará. (Salmo 23:1)",
  "Os que confiam no Senhor são como o monte Sião, que não se abala. (Salmo 125:1)",
  "Clama a mim e responder-te-ei e anunciar-te-ei coisas grandes e firmes. (Jeremias 33:3)",
  "Busca primeiro o Reino de Deus, e todas as coisas te serão acrescentadas. (Mateus 6:33)",
  "Tudo posso naquele que me fortalece. (Filipenses 4:13)",
  "O justo viverá da fé. (Romanos 1:17)",
  "Porque Deus não nos deu espírito de medo, mas de poder, amor e equilíbrio. (2 Timóteo 1:7)",
  "Esforça-te e tem bom ânimo. (Josué 1:9)",
  "Se creres, verás a glória de Deus. (João 11:40)",
  "A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos. (Hebreus 11:1)",
"O Senhor é o meu pastor, nada me faltará. (Salmo 23:1)",
"Os que confiam no Senhor são como o monte Sião, que não se abala. (Salmo 125:1)",
"Clama a mim e responder-te-ei e anunciar-te-ei coisas grandes e firmes. (Jeremias 33:3)",
"Busca primeiro o Reino de Deus, e todas as coisas te serão acrescentadas. (Mateus 6:33)",
"Tudo posso naquele que me fortalece. (Filipenses 4:13)",
"O justo viverá da fé. (Romanos 1:17)",
"Porque Deus não nos deu espírito de medo, mas de poder, amor e equilíbrio. (2 Timóteo 1:7)",
"Esforça-te e tem bom ânimo. (Josué 1:9)",
"Se creres, verás a glória de Deus. (João 11:40)",
"Acima de tudo, porém, revistam-se do amor, que é o elo perfeito. (Colossenses 3:14)",
"Como é bom e agradável quando os irmãos vivem em união! (Salmo 133:1)",
"O temor do Senhor é o princípio da sabedoria. (Provérbios 9:10)",
"Honra ao Senhor com os teus bens e com as primícias de toda a tua renda. (Provérbios 3:9)",
"Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de bom ânimo, e nada lhes reprova; e ser-lhe-á concedida. (Tiago 1:5)",
"Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. (Filipenses 4:6)",
"Lança o teu fardo sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado. (Salmo 55:22)",
"Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará. (Salmo 37:5)",
"O coração alegre aformoseia o rosto, mas pela dor do coração o espírito se abate. (Provérbios 15:13)",
"Porque onde estiver o vosso tesouro, aí estará também o vosso coração. (Mateus 6:21)",
"Amarás o teu próximo como a ti mesmo. (Marcos 12:31)",
"O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. (1 Coríntios 13:4)",
"Melhor é serem dois do que um. (Eclesiastes 4:9)",
"A inteligência do homem prolonga a sua vida, mas a estultícia dos tolos os destrói. (Provérbios 10:23)",
"Deleita-te também no Senhor, e ele te concederá os desejos do teu coração. (Salmo 37:4)",
"Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. (Mateus 11:28)",
"Não te deixarei, nem te desampararei. (Hebreus 13:5)",
"Sê forte e corajoso! Não te apavores, nem te desanimes, pois o Senhor, o teu Deus, estará contigo por onde quer que andares. (Josué 1:9)",
"O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e te dê a paz. (Números 6:24-26)",
"Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu. (Eclesiastes 3:1)",
"Feliz é o homem que acha a sabedoria, e o homem que adquire conhecimento. (Provérbios 3:13)",
"Cada um contribua segundo propôs no seu coração; não com tristeza, ou por necessidade; porque Deus ama ao que dá com alegria. (2 Coríntios 9:7)",
"O dinheiro é a defesa, e a sabedoria é a defesa, mas a excelência do conhecimento é que a sabedoria dá vida aos que a possuem. (Eclesiastes 7:12)",
"Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal. (Mateus 6:34)",
"Vinde, benditos de meu Pai, possuí por herança o reino que vos está preparado desde a fundação do mundo. (Mateus 25:34)",
"Pois onde estiver o seu tesouro, aí também estará o seu coração. (Lucas 12:34)",
"Alegrai-vos sempre no Senhor; outra vez digo, alegrai-vos. (Filipenses 4:4)",
"Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não veem. (Hebreus 11:1)",
"O Senhor é a minha luz e a minha salvação; a quem temerei? (Salmo 27:1)",
"Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. (Salmo 91:1)",
"Mil cairão ao teu lado, e dez mil à tua direita, mas tu não serás atingido. (Salmo 91:7)",
"O justo florescerá como a palmeira; crescerá como o cedro no Líbano. (Salmo 92:12)",
"Aproximem-se de Deus, e ele se aproximará de vocês. (Tiago 4:8)",
"O Senhor é bom, uma fortaleza no dia da angústia; e conhece os que nele confiam. (Naum 1:7)",
"Mas buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas. (Mateus 6:33)",
"Vinde a mim, todos os que estais cansados e oprimidos, e eu vos darei descanso. (Mateus 11:28)",
"Eu sou o caminho, e a verdade, e a vida; ninguém vem ao Pai, senão por mim. (João 14:6)",
"E tudo o que pedirdes em meu nome, eu o farei, para que o Pai seja glorificado no Filho. (João 14:13)",
"No mundo tereis aflições, mas tende bom ânimo, eu venci o mundo. (João 16:33)",
"Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus. (Efésios 2:8)",
"Posso todas as coisas naquele que me fortalece. (Filipenses 4:13)",
"Combati o bom combate, terminei a corrida, guardei a fé. (2 Timóteo 4:7)",
"Porque onde dois ou três se reúnem em meu nome, aí estou eu no meio deles. (Mateus 18:20)",
"Melhor é o pouco com justiça, do que grandes rendas com injustiça. (Provérbios 16:8)",
"Em todo o tempo ama o amigo e na angústia se faz o irmão. (Provérbios 17:17)",
"A resposta branda desvia o furor, mas a palavra dura suscita a ira. (Provérbios 15:1)",
"Aquele que é fiel no pouco, também é fiel no muito. (Lucas 16:10)",
"Não ameis o mundo, nem o que no mundo há. Se alguém ama o mundo, o amor do Pai não está nele. (1 João 2:15)",
"Porque Deus amou o mundo de tal maneira que deu o seu Filho unigénito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna. (João 3:16)",
"O Senhor é bom para com aqueles que esperam por ele, para com aqueles que o buscam. (Lamentações 3:25)",
"O fruto do Espírito é: amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. (Gálatas 5:22-23)",
"Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento. (Provérbios 3:5)",
"Em todos os teus caminhos reconhece-o, e ele endireitará as tuas veredas. (Provérbios 3:6)",
"Não sejas sábio aos teus próprios olhos; teme ao Senhor e aparta-te do mal. (Provérbios 3:7)",
"Isto trará saúde ao teu corpo e refrigério aos teus ossos. (Provérbios 3:8)",
"Abençoado é o homem que persevera na provação, porque depois de aprovado, receberá a coroa da vida que Deus prometeu aos que o amam. (Tiago 1:12)",
"Mas se alguém tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de bom ânimo, e nada lhes reprova; e ser-lhe-á concedida. (Tiago 1:5)",
"A oração feita por um justo pode muito em seus efeitos. (Tiago 5:16)",
"Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. (1 Pedro 5:7)",
"O teu mandamento me faz mais sábio que os meus inimigos, pois está sempre comigo. (Salmo 119:98)",
"A lei do Senhor é perfeita, e restaura a alma; o testemunho do Senhor é fiel, e dá sabedoria aos símplices. (Salmo 19:7)",
"Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus. (1 Coríntios 1:18)",
"Mas Deus escolheu as coisas loucas deste mundo para confundir as sábias; e Deus escolheu as coisas fracas deste mundo para confundir as fortes. (1 Coríntios 1:27)",
"Porque a sabedoria deste mundo é loucura diante de Deus. (1 Coríntios 3:19)",
"E tudo o que fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens. (Colossenses 3:23)",
"Porque para mim o viver é Cristo e o morrer é ganho. (Filipenses 1:21)",
"Aquele que nem mesmo a seu próprio Filho poupou, antes o entregou por todos nós, como nos não dará também com ele todas as coisas? (Romanos 8:32)",
"Em todas estas coisas, somos mais que vencedores, por meio daquele que nos amou. (Romanos 8:37)",
"Pois estou convencido de que nem a morte nem a vida, nem anjos nem demónios, nem o presente nem o futuro, nem quaisquer poderes, nem altura nem profundidade, nem qualquer outra coisa em toda a criação será capaz de nos separar do amor de Deus que está em Cristo Jesus, nosso Senhor. (Romanos 8:38-39)",
"Ora, sem fé é impossível agradar a Deus; porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é galardoador dos que o buscam. (Hebreus 11:6)",
"Porque não temos um sumo sacerdote que não possa compadecer-se das nossas fraquezas; antes, foi ele tentado em todas as coisas, à nossa semelhança, mas sem pecado. (Hebreus 4:15)",
"Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça, a fim de sermos ajudados em tempo oportuno. (Hebreus 4:16)",
"Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós. (Tiago 4:7)",
"Humilhai-vos, portanto, debaixo da potente mão de Deus, para que, a seu tempo, vos exalte. (1 Pedro 5:6)",
"Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. (1 Pedro 5:7)",
"E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus. (Filipenses 4:7)",
"Regozijai-vos na esperança, sede pacientes na tribulação, perseverai na oração. (Romanos 12:12)",
"Nunca se afaste de você a benignidade e a fidelidade; prenda-as ao seu pescoço, escreva-as na tábua do seu coração. (Provérbios 3:3)",
"Assim você encontrará favor e boa reputação aos olhos de Deus e dos homens. (Provérbios 3:4)",
"Um coração alegre é um bom remédio, mas um espírito abatido seca os ossos. (Provérbios 17:22)",
"Alegrai-vos sempre no Senhor. Outra vez digo: Alegrai-vos! (Filipenses 4:4)",
"Se, pois, o Filho vos libertar, verdadeiramente sereis livres. (João 8:36)",
"Porque onde estiver o vosso tesouro, aí estará também o vosso coração. (Mateus 6:21)",
"Dêem, e lhes será dado; boa medida, recalcada, sacudida e transbordante, vos deitarão no vosso regaço; porque com a mesma medida com que medirdes, vos tornarão a medir. (Lucas 6:38)",
"Não vos deixeis vencer do mal, mas vencei o mal com o bem. (Romanos 12:21)",
"Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor. (1 Coríntios 15:58)",
"Porque somos cooperadores de Deus; vós sois lavoura de Deus e edifício de Deus. (1 Coríntios 3:9)",
"Em tudo somos atribulados, mas não angustiados; perplexos, mas não desesperados; perseguidos, mas não desamparados; abatidos, mas não destruídos. (2 Coríntios 4:8-9)",
"Mas temos este tesouro em vasos de barro, para que a excelência do poder seja de Deus, e não de nós. (2 Coríntios 4:7)",
"Porque andamos por fé, e não por vista. (2 Coríntios 5:7)",
"Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo. (2 Coríntios 5:17)",
"Em nada vos inquieteis; antes, em tudo pela oração e súplicas, com ação de graças, sejam os vossos pedidos conhecidos diante de Deus. (Filipenses 4:6)",
"Pela sua benignidade, o Senhor nos dá a vida; pela sua fidelidade, nos guarda. (Salmo 25:10)",
"O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus é o meu rochedo, em quem me refugio. (Salmo 18:2)",
"Bendito o homem que confia no Senhor, e cuja esperança é o Senhor. (Jeremias 17:7)",
"Ensina-nos a contar os nossos dias, de tal maneira que alcancemos corações sábios. (Salmo 90:12)",
"A quem temos no céu senão a ti? E na terra não há quem eu deseje além de ti. (Salmo 73:25)",
"A tua palavra é lâmpada para os meus pés e luz para o meu caminho. (Salmo 119:105)",
"Esforça-te e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares. (Josué 1:9)",
"Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares. (Deuteronômio 31:6)",
"O Senhor não retarda a sua promessa, ainda que alguns a considerem demorada. Pelo contrário, ele é paciente para convosco, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento. (2 Pedro 3:9)",
"Mas o fim de todas as coisas está próximo; sede, portanto, sensatos e sóbrios para as orações. (1 Pedro 4:7)",
"Acima de tudo, porém, tende ardente amor uns para com os outros, porque o amor cobre a multidão de pecados. (1 Pedro 4:8)",
"Sede mutuamente hospitaleiros, sem murmuração. (1 Pedro 4:9)",
"Servi uns aos outros, cada um conforme o dom que recebeu, como bons despenseiros da multiforme graça de Deus. (1 Pedro 4:10)",
"Aquele que fala, fale como entregando a palavra de Deus; aquele que ministra, ministre segundo a força que Deus concede, para que em tudo Deus seja glorificado por meio de Jesus Cristo, a quem pertencem a glória e o domínio pelos séculos dos séculos. Amém. (1 Pedro 4:11)",
"Amados, não estranheis a ardente prova que vem sobre vós para vos tentar, como se coisa estranha vos acontecesse. (1 Pedro 4:12)",
"Antes, alegrai-vos por serdes participantes das aflições de Cristo; para que também na revelação da sua glória vos regozijeis com alegria exorbitante. (1 Pedro 4:13)",
"Bem-aventurados sois vós, quando vos injuriarem e perseguirem e, mentindo, disserem todo o mal contra vós por minha causa. (Mateus 5:11)",
"Alegrai-vos e exultai, porque é grande o vosso galardão nos céus; porque assim perseguiram os profetas que foram antes de vós. (Mateus 5:12)",
"Vós sois o sal da terra; e se o sal for insípido, com que se há de salgar? Para nada mais presta senão para se lançar fora, e ser pisado pelos homens. (Mateus 5:13)",
"Vós sois a luz do mundo; não se pode esconder uma cidade edificada sobre um monte. (Mateus 5:14)",
"Nem se acende uma candeia e se coloca debaixo do alqueire, mas no velador, e dá luz a todos que estão na casa. (Mateus 5:15)",
"Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai, que está nos céus. (Mateus 5:16)",
"Não pensem que vim destruir a Lei ou os Profetas. Não vim destruir, mas cumprir. (Mateus 5:17)",
"Na verdade vos digo que, até que o céu e a terra passem, nem um jota ou um til se omitirá da lei, sem que tudo seja cumprido. (Mateus 5:18)",
"Todo aquele, pois, que anular um destes mais pequenos mandamentos e assim ensinar aos homens, será chamado o menor no reino dos céus; mas qualquer que os cumprir e ensinar será chamado grande no reino dos céus. (Mateus 5:19)",
"Porque vos digo que, se a vossa justiça não exceder a dos escribas e fariseus, de modo nenhum entrareis no reino dos céus. (Mateus 5:20)",
"Tende bom ânimo, eu venci o mundo. (João 16:33)",
"Eu te louvarei, Senhor, de todo o meu coração; contarei todas as tuas maravilhas. (Salmo 9:1)",
"A minha alma se alegra no Senhor; regozija-se na sua salvação. (Salmo 35:9)",
"O Senhor é a minha força e o meu escudo; nele o meu coração confiou, e fui socorrido; assim o meu coração salta de prazer, e com o meu canto o louvarei. (Salmo 28:7)",
"Ouve, Israel, o Senhor nosso Deus é o único Senhor. (Deuteronômio 6:4)",
"Amarás, pois, o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças. (Deuteronômio 6:5)",
"Estas palavras que hoje te ordeno, estarão no teu coração. (Deuteronômio 6:6)",
"E as ensinarás a teus filhos, e delas falarás assentado em tua casa, e andando pelo caminho, e deitando-te, e levantando-te. (Deuteronômio 6:7)",
"Também as atarás por sinal na tua mão, e te serão por frontais entre os teus olhos. (Deuteronômio 6:8)",
"E as escreverás nos umbrais de tua casa, e nas tuas portas. (Deuteronômio 6:9)",
"E conhecerão todos que sois meus discípulos, se tiverdes amor uns pelos outros. (João 13:35)",
"Permanecei em mim, e eu permanecerei em vós. Como o ramo não pode dar fruto por si mesmo, se não permanecer na videira, assim também vós, se não permanecerdes em mim. (João 15:4)",
"Eu sou a videira, vós as varas; quem está em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer. (João 15:5)",
"Se guardardes os meus mandamentos, permanecereis no meu amor; do mesmo modo que eu tenho guardado os mandamentos de meu Pai, e permaneço no seu amor. (João 15:10)",
"Estas coisas vos tenho dito para que a minha alegria permaneça em vós, e a vossa alegria seja completa. (João 15:11)",
"O meu mandamento é este: que vos ameis uns aos outros, assim como eu vos amei. (João 15:12)",
"Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos. (João 15:13)",
"Vós sois meus amigos, se fizerdes o que eu vos mando. (João 15:14)",
"Já vos não chamarei servos, porque o servo não sabe o que faz o seu senhor; mas tenho-vos chamado amigos, porque tudo quanto ouvi de meu Pai vos tenho feito conhecer. (João 15:15)",
"Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto, e o vosso fruto permaneça; a fim de que tudo quanto em meu nome pedirdes ao Pai ele vo-lo conceda. (João 15:16)",
"Isto vos mando, que vos ameis uns aos outros. (João 15:17)",
"Se o mundo vos odeia, sabei que, primeiro do que a vós, me odiou a mim. (João 15:18)",
"Se fôsseis do mundo, o mundo amaria o que é seu; mas porque não sois do mundo, antes eu vos escolhi do mundo, por isso o mundo vos odeia. (João 15:19)",
"Lembrai-vos da palavra que vos disse: Não é o servo maior do que o seu senhor. Se a mim me perseguiram, também vos perseguirão a vós; se guardaram a minha palavra, também guardarão a vossa. (João 15:20)",
"Mas tudo isto vos farão por causa do meu nome, porque não conhecem aquele que me enviou. (João 15:21)",
"Não vos deixarei órfãos; virei para vós. (João 14:18)",
"Aquele que tem os meus mandamentos e os guarda, esse é o que me ama; e aquele que me ama será amado de meu Pai, e eu o amarei, e me manifestarei a ele. (João 14:21)",
"Se alguém me ama, guardará a minha palavra, e meu Pai o amará, e viremos para ele, e faremos nele morada. (João 14:23)",
"Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize. (João 14:27)",
"Porque Deus é amor. (1 João 4:8)",
"Nisto se manifestou o amor de Deus em nós: em que Deus enviou seu Filho unigénito ao mundo, para que por ele vivamos. (1 João 4:9)",
"Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou a nós, e enviou seu Filho para propiciação pelos nossos pecados. (1 João 4:10)",
"Amados, se Deus assim nos amou, também nós devemos amar uns aos outros. (1 João 4:11)",
"Ninguém jamais viu a Deus; se nos amamos uns aos outros, Deus permanece em nós, e o seu amor é aperfeiçoado em nós. (1 João 4:12)",
"Nisto conhecemos que permanecemos nele, e ele em nós: por ele nos ter dado do seu Espírito. (1 João 4:13)",
"E nós temos visto e testificamos que o Pai enviou seu Filho para Salvador do mundo. (1 João 4:14)",
"Quem confessar que Jesus é o Filho de Deus, Deus permanece nele, e ele em Deus. (1 João 4:15)",
"E nós conhecemos e cremos no amor que Deus nos tem. Deus é amor; e quem permanece no amor, permanece em Deus, e Deus nele. (1 João 4:16)",
"Nisto é perfeito o amor para connosco, para que no dia do juízo tenhamos confiança; porque, qual ele é, somos nós também neste mundo. (1 João 4:17)",
"No amor não há temor, antes o perfeito amor lança fora o temor; porque o temor tem consigo pena. E o que teme não é perfeito em amor. (1 João 4:18)",
"Nós amamos, porque ele nos amou primeiro. (1 João 4:19)",
"Se alguém diz: Eu amo a Deus, e odeia a seu irmão, é mentiroso. Pois quem não ama a seu irmão, a quem vê, como pode amar a Deus, a quem não vê? (1 João 4:20)",
"E este mandamento temos dele: que quem ama a Deus, ame também a seu irmão. (1 João 4:21)",
"Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé. (1 João 5:4)",
"Quem é que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus? (1 João 5:5)",
"Aquele que pratica a justiça é justo, assim como ele é justo. (1 João 3:7)",
"Quem não pratica a justiça não procede de Deus, nem aquele que não ama a seu irmão. (1 João 3:10)",
"Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros. (1 João 3:11)",
"Filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade. (1 João 3:18)",
"E nisto conhecemos que somos da verdade, e confortaremos diante dele o nosso coração. (1 João 3:19)",
"Porque se o nosso coração nos condena, maior é Deus do que o nosso coração, e conhece todas as coisas. (1 João 3:20)",
"Amados, se o nosso coração nos não condena, temos confiança para com Deus. (1 João 3:21)",
"E qualquer coisa que lhe pedirmos, dele a receberemos, porque guardamos os seus mandamentos, e fazemos o que é agradável à sua vista. (1 João 3:22)",
"E o seu mandamento é este: que creiamos no nome de seu Filho Jesus Cristo, e nos amemos uns aos outros, segundo o mandamento que nos deu. (1 João 3:23)",
"E aquele que guarda os seus mandamentos permanece em Deus, e Deus nele. E nisto conhecemos que ele permanece em nós: pelo Espírito que nos deu. (1 João 3:24)",
"E Deus é poderoso para fazer abundar em vós toda a graça, a fim de que, tendo sempre, em tudo, toda a suficiência, abundeis em toda a boa obra. (2 Coríntios 9:8)",
"Para que em tudo enriqueçais para toda a beneficência, a qual faz que por nós se dêem graças a Deus. (2 Coríntios 9:11)",
"Porque o amor ao dinheiro é a raiz de todos os males; e alguns, por cobiçá-lo, se desviaram da fé e se torturaram com muitos sofrimentos. (1 Timóteo 6:10)",
"Mas tu, ó homem de Deus, foge destas coisas e segue a justiça, a piedade, a fé, o amor, a perseverança e a mansidão. (1 Timóteo 6:11)",
"Combate o bom combate da fé. Toma posse da vida eterna, para a qual também foste chamado, e fizeste a boa confissão perante muitas testemunhas. (1 Timóteo 6:12)",
"Para que os seus corações sejam consolados, e estejam unidos em amor, e enriquecidos da plenitude do entendimento, para o conhecimento do mistério de Deus e Pai, e de Cristo. (Colossenses 2:2)",
"Em quem estão escondidos todos os tesouros da sabedoria e do conhecimento. (Colossenses 2:3)",
"Assim como recebestes a Cristo Jesus, o Senhor, continuai a viver nele. (Colossenses 2:6)",
"Enraizados e edificados nele, e confirmados na fé, assim como vos foi ensinado, crescendo em ação de graças. (Colossenses 2:7)",
"Tende cuidado para que ninguém vos engane com filosofias e vãs subtilezas, conforme a tradição dos homens, conforme os rudimentos do mundo, e não segundo Cristo. (Colossenses 2:8)",
"Porque nele habita corporalmente toda a plenitude da divindade. (Colossenses 2:9)",
"E estais completos nele, que é a cabeça de todo o principado e potestade. (Colossenses 2:10)",
"Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica, com ação de graças. (Filipenses 4:6)",
"E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus. (Filipenses 4:7)",
"Finalmente, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisto pensai. (Filipenses 4:8)",
"O que também aprendestes, e recebestes, e ouvistes e vistes em mim, isso fazei; e o Deus de paz será convosco. (Filipenses 4:9)",
"Eu sei estar abatido, e sei também ter abundância; em toda a maneira, e em todas as coisas estou instruído, tanto a ter fartura, como a ter fome; tanto a ter abundância, como a padecer necessidade. (Filipenses 4:12)",
"Posso todas as coisas em Cristo que me fortalece. (Filipenses 4:13)",
"Não digas: Vingar-me-ei do mal; espera pelo Senhor, e ele te livrará. (Provérbios 20:22)",
"Enganosa é a graça, e vã é a formosura, mas a mulher que teme ao Senhor, essa será louvada. (Provérbios 31:30)",
"Dai-lhe do fruto das suas mãos, e as suas obras a louvem nas portas. (Provérbios 31:31)",
"Porque o Senhor dá a sabedoria; da sua boca vem o conhecimento e o entendimento. (Provérbios 2:6)",
"Ele reserva a verdadeira sabedoria para os retos; é escudo para os que caminham na sinceridade. (Provérbios 2:7)",
"Para que guardes os caminhos da justiça, e conserves o caminho dos seus santos. (Provérbios 2:8)",
"Então entenderás a justiça, e o juízo, e a equidade, e todas as boas veredas. (Provérbios 2:9)",
"Porque a sabedoria entrará no teu coração, e o conhecimento será agradável à tua alma. (Provérbios 2:10)",
"O bom siso te guardará, o entendimento te protegerá. (Provérbios 2:11)",
"Para te livrar do mau caminho, e do homem que fala coisas perversas. (Provérbios 2:12)",
"Daqueles que deixam as veredas da retidão para andarem pelos caminhos das trevas. (Provérbios 2:13)",
"Que se alegram em fazer o mal e se deleitam na perversidade. (Provérbios 2:14)",
"Cujos caminhos são tortuosos e pervertidos em suas veredas. (Provérbios 2:15)",
"Para te livrar da mulher estranha, da estrangeira que lisonjeia com suas palavras. (Provérbios 2:16)",
"Que abandona o guia da sua mocidade e se esquece da aliança do seu Deus. (Provérbios 2:17)",
"Porque a sua casa se inclina para a morte, e as suas veredas para o inferno. (Provérbios 2:18)",
"Todos os que a procuram não voltarão, e não atingirão as veredas da vida. (Provérbios 2:19)",
"Para que andes pelos caminhos dos bons e guardes as veredas dos justos. (Provérbios 2:20)",
"Porque os retos habitarão a terra, e os íntegros permanecerão nela. (Provérbios 2:21)",
"Mas os ímpios serão arrancados da terra, e os desleais serão dela exterminados. (Provérbios 2:22)",
"Filho meu, não te esqueças da minha lei, e o teu coração guarde os meus mandamentos. (Provérbios 3:1)",
"Porque eles te darão o prolongamento dos dias, e anos de vida e paz. (Provérbios 3:2)",
"Não deixes que a benignidade e a verdade te abandonem; ata-as ao pescoço; escreve-as na tábua do teu coração. (Provérbios 3:3)",
"E acharás graça e bom entendimento à vista de Deus e dos homens. (Provérbios 3:4)",
"Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. (Provérbios 3:5)",
"Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas. (Provérbios 3:6)",
"Não sejas sábio aos teus próprios olhos; teme ao Senhor e aparta-te do mal. (Provérbios 3:7)",
"Isso trará saúde para o teu corpo e refrigério para os teus ossos. (Provérbios 3:8)",
"Honra ao Senhor com os teus bens e com as primícias de toda a tua renda. (Provérbios 3:9)",
"Assim se encherão de fartura os teus celeiros, e os teus lagares transbordarão de mosto. (Provérbios 3:10)",
"Filho meu, não rejeites a correção do Senhor, nem te enfades da sua repreensão. (Provérbios 3:11)",
"Porque o Senhor repreende aquele a quem ama, assim como o pai ao filho a quem quer bem. (Provérbios 3:12)",
"Bem-aventurado o homem que encontra sabedoria, e o homem que adquire discernimento. (Provérbios 3:13)",
"Porque melhor é a sua mercadoria do que a de prata, e a sua renda do que o ouro mais fino. (Provérbios 3:14)",
"Mais preciosa é do que os rubis; e tudo o que podes desejar não se pode comparar a ela. (Provérbios 3:15)",
"Vida longa está na sua mão direita; na sua mão esquerda, riquezas e honra. (Provérbios 3:16)",
"Os seus caminhos são caminhos de delícias, e todas as suas veredas são paz. (Provérbios 3:17)",
"É árvore da vida para os que a abraçam; e bem-aventurados são todos os que a retêm. (Provérbios 3:18)",
"O Senhor, com sabedoria, fundou a terra; com inteligência, firmou os céus. (Provérbios 3:19)",
"Pelo seu conhecimento os abismos se abriram, e as nuvens destilam o orvalho. (Provérbios 3:20)",
"Filho meu, não se apartem estas coisas dos teus olhos; guarda a verdadeira sabedoria e o discernimento. (Provérbios 3:21)",
"Porque serão vida para a tua alma, e graça para o teu pescoço. (Provérbios 3:22)",
"Então andarás seguro no teu caminho, e o teu pé não tropeçará. (Provérbios 3:23)",
"Quando te deitares, não temerás; sim, deitar-te-ás, e o teu sono será suave. (Provérbios 3:24)",
"Não temerás o pavor repentino, nem a ruína dos ímpios, quando vier. (Provérbios 3:25)",
"Porque o Senhor será a tua confiança, e guardará o teu pé de ser preso. (Provérbios 3:26)",
"Não negues o bem a quem de direito, estando na tua mão a capacidade de o fazer. (Provérbios 3:27)",
"Não digas ao teu próximo: Vai, e volta, e amanhã to darei; quando tens contigo. (Provérbios 3:28)",
"Não maquines o mal contra o teu próximo, pois ele habita seguro junto de ti. (Provérbios 3:29)",
"Não contendas com alguém sem razão, se não te fez mal algum. (Provérbios 3:30)",
"Não invejes o homem violento, nem escolhas nenhum dos seus caminhos. (Provérbios 3:31)",
"Porque o perverso é abominação para o Senhor, mas com os sinceros ele tem intimidade. (Provérbios 3:32)",
"A maldição do Senhor está na casa do ímpio, mas ele abençoa a morada dos justos. (Provérbios 3:33)",
"Certamente ele escarnece dos escarnecedores, mas dá graça aos humildes. (Provérbios 3:34)",
"Os sábios herdarão glória, mas a vergonha é a recompensa dos loucos. (Provérbios 3:35)",
"Guarda-me, ó Deus, porque em ti confio. (Salmo 16:1)",
"O Senhor é a porção da minha herança e do meu cálice; tu sustentas a minha sorte. (Salmo 16:5)",
"Os limites caíram-me em lugares prazerosos; deveras, tenho uma boa herança. (Salmo 16:6)",
"Bendirei o Senhor que me aconselha; até de noite o meu coração me ensina. (Salmo 16:7)",
"Tenho posto o Senhor continuamente diante de mim; porquanto ele está à minha direita, nunca serei abalado. (Salmo 16:8)",
"Portanto, o meu coração se alegra, e a minha alma exulta; também a minha carne habitará em segurança. (Salmo 16:9)",
"Pois não deixarás a minha alma na sepultura, nem permitirás que o teu Santo veja corrupção. (Salmo 16:10)",
"Tu me farás ver a vereda da vida; na tua presença há plenitude de alegria; na tua destra há delícias perpetuamente. (Salmo 16:11)",
"O Senhor é o meu pastor, nada me faltará. (Salmo 23:1)",
"Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas. (Salmo 23:2)",
"Refrigera a minha alma; guia-me pelas veredas da justiça por amor do seu nome. (Salmo 23:3)",
"Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, porque tu estás comigo; o teu bordão e o teu cajado me consolam. (Salmo 23:4)",
"Preparas uma mesa perante mim na presença dos meus inimigos; unges com óleo a minha cabeça; o meu cálice transborda. (Salmo 23:5)",
"Certamente a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na casa do Senhor por longos dias. (Salmo 23:6)",
"Elevo os meus olhos para os montes; de onde me virá o socorro? (Salmo 121:1)",
"O meu socorro vem do Senhor, que fez os céus e a terra. (Salmo 121:2)",
"Não deixará vacilar o teu pé; aquele que te guarda não dormitará. (Salmo 121:3)",
"Eis que não dormitará nem dormirá aquele que guarda a Israel. (Salmo 121:4)",
"O Senhor é quem te guarda; o Senhor é a tua sombra à tua direita. (Salmo 121:5)",
"De dia não te molestará o sol, nem de noite a lua. (Salmo 121:6)",
"O Senhor te guardará de todo o mal; guardará a tua alma. (Salmo 121:7)",
"O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre. (Salmo 121:8)",
"Agrada-te do Senhor, e ele satisfará os desejos do teu coração. (Salmo 37:4)",
"Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará. (Salmo 37:5)",
"Ele fará sobressair a tua justiça como a luz, e o teu direito como o meio-dia. (Salmo 37:6)",
"Descansa no Senhor, e espera nele; não te irrites por causa daquele que prospera em seu caminho, por causa do homem que executa planos perversos. (Salmo 37:7)",
"Deixa a ira, e abandona o furor; não te indignes de forma alguma para fazer o mal. (Salmo 37:8)",
"Porque os malfeitores serão desarraigados; mas aqueles que esperam no Senhor herdarão a terra. (Salmo 37:9)",
"Um pouco, e já não existirá o ímpio; sim, procurarás o seu lugar, e não o acharás. (Salmo 37:10)",
"Mas os mansos herdarão a terra, e se deleitarão na abundância de paz. (Salmo 37:11)",
"O ímpio maquina contra o justo e range contra ele os dentes. (Salmo 37:12)",
"O Senhor se rirá dele, pois vê que vem chegando o seu dia. (Salmo 37:13)",
"Os ímpios sacam da espada e entesam o arco, para derrubarem o pobre e necessitado, e para matarem os de reto caminho. (Salmo 37:14)",
"Mas a sua espada lhes entrará no coração, e os seus arcos se quebrarão. (Salmo 37:15)",
"Mais vale o pouco do justo do que a riqueza de muitos ímpios. (Salmo 37:16)",
"Pois os braços dos ímpios serão quebrados, mas o Senhor sustenta os justos. (Salmo 37:17)",
"O Senhor conhece os dias dos íntegros, e a sua herança permanecerá para sempre. (Salmo 37:18)",
"Não serão envergonhados nos maus tempos, e nos dias da fome se fartarão. (Salmo 37:19)",
"Mas os ímpios perecerão; e os inimigos do Senhor serão como a gordura dos cordeiros; desaparecerão, sim, em fumaça se desfarão. (Salmo 37:20)",
"O ímpio pede emprestado, e não paga; mas o justo se compadece e dá. (Salmo 37:21)",
"Pois aqueles a quem ele abençoa herdarão a terra, mas aqueles a quem amaldiçoa serão exterminados. (Salmo 37:22)",
"Os passos de um homem bom são confirmados pelo Senhor, e ele deleita-se no seu caminho. (Salmo 37:23)",
"Ainda que caia, não ficará prostrado, pois o Senhor o segura pela mão. (Salmo 37:24)",
"Fui moço, e agora sou velho; mas nunca vi o justo desamparado, nem a sua descendência a mendigar o pão. (Salmo 37:25)",
"Dá sempre com liberalidade, e a sua descendência é abençoada. (Salmo 37:26)",
"Aparta-te do mal, e faze o bem; e terás morada para sempre. (Salmo 37:27)",
"Pois o Senhor ama a justiça e não desampara os seus santos; eles serão preservados para sempre, mas a descendência dos ímpios será exterminada. (Salmo 37:28)",
"Os justos herdarão a terra e nela habitarão para sempre. (Salmo 37:29)",
"A boca do justo profere sabedoria, e a sua língua fala o que é reto. (Salmo 37:30)",
"A lei do seu Deus está em seu coração; os seus passos não resvalarão. (Salmo 37:31)",
"O ímpio espreita o justo e procura matá-lo. (Salmo 37:32)",
"O Senhor não o deixará em suas mãos, nem o condenará quando for julgado. (Salmo 37:33)",
"Espera no Senhor, e guarda o seu caminho, e ele te exaltará para herdares a terra; verás quando os ímpios forem exterminados. (Salmo 37:34)",
"Vi o ímpio muito engrandecido e que se estendia como a árvore verde na terra natal. (Salmo 37:35)",
"Mas ele passou, e eis que não era mais; procurei-o, mas não foi encontrado. (Salmo 37:36)",
"Observa o homem íntegro, e atenta para o que é reto; porque o fim desse homem será paz. (Salmo 37:37)",
"Quanto aos transgressores, serão à uma destruídos; o fim dos ímpios será o extermínio. (Salmo 37:38)",
"Mas a salvação dos justos vem do Senhor; ele é a sua fortaleza no tempo da angústia. (Salmo 37:39)",
"O Senhor os ajuda e os livra; ele os livra dos ímpios e os salva, porquanto nele confiam. (Salmo 37:40)",
"Ora, o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo. (Romanos 15:13)",
"Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu. (Eclesiastes 3:1)",
"Tempo de nascer, e tempo de morrer; tempo de plantar, e tempo de arrancar o que se plantou. (Eclesiastes 3:2)",
"Tempo de matar, e tempo de curar; tempo de derrubar, e tempo de edificar. (Eclesiastes 3:3)",
"Tempo de chorar, e tempo de rir; tempo de prantear, e tempo de dançar. (Eclesiastes 3:4)",
"Tempo de espalhar pedras, e tempo de ajuntar pedras; tempo de abraçar, e tempo de abster-se de abraçar. (Eclesiastes 3:5)",
"Tempo de buscar, e tempo de perder; tempo de guardar, e tempo de lançar fora. (Eclesiastes 3:6)",
"Tempo de rasgar, e tempo de costurar; tempo de calar, e tempo de falar. (Eclesiastes 3:7)",
"Tempo de amar, e tempo de odiar; tempo de guerra, e tempo de paz. (Eclesiastes 3:8)",
"Que proveito tem o trabalhador naquilo em que trabalha? (Eclesiastes 3:9)",
"Vi o trabalho que Deus deu aos filhos dos homens, para nele se ocuparem. (Eclesiastes 3:10)",
"Tudo fez formoso em seu tempo; também pôs no coração do homem o sentido da eternidade, embora este não possa perceber a obra que Deus faz desde o princípio até o fim. (Eclesiastes 3:11)",
"Sei que não há nada melhor para o homem do que alegrar-se e fazer o bem enquanto vive. (Eclesiastes 3:12)",
"E também que todo o homem coma e beba, e goze do bem de todo o seu trabalho; isso é dom de Deus. (Eclesiastes 3:13)",
"Sei que tudo quanto Deus faz durará para sempre; nada se lhe pode acrescentar, e nada se lhe pode tirar; e isto faz Deus para que os homens temam diante dele. (Eclesiastes 3:14)",
"O que é, já foi; e o que há de ser, também já foi; e Deus pede conta do que passou. (Eclesiastes 3:15)",
"Vi mais debaixo do sol que no lugar da justiça havia impiedade, e no lugar da retidão havia maldade. (Eclesiastes 3:16)",
"Então disse eu no meu coração: Deus julgará o justo e o ímpio; porque há um tempo para todo o propósito e para toda a obra. (Eclesiastes 3:17)",
"Disse eu no meu coração: É por causa dos filhos dos homens, para que Deus possa prová-los, e para que vejam que são como os animais. (Eclesiastes 3:18)",
"Pois o que acontece com os filhos dos homens acontece com os animais; o mesmo fôlego têm todos; e semelhança nenhuma tem o homem sobre os animais; porque tudo é vaidade. (Eclesiastes 3:19)",
"Todos vão para o mesmo lugar; todos procedem do pó, e ao pó todos tornarão. (Eclesiastes 3:20)",
"Quem sabe se o espírito dos filhos dos homens sobe para cima, e se o espírito dos animais desce para baixo da terra? (Eclesiastes 3:21)",
"Assim que tenho visto que não há nada melhor para o homem do que alegrar-se nas suas obras, porque essa é a sua porção; pois quem o levará para ver o que será depois dele? (Eclesiastes 3:22)",
"Onde há contenda, há transgressão; mas a sabedoria está com os que se aconselham. (Provérbios 13:10)",
"A riqueza adquirida apressadamente diminuirá, mas quem a ajunta pouco a pouco, com trabalho, a aumentará. (Provérbios 13:11)",
"A esperança adiada entristece o coração, mas o desejo cumprido é árvore de vida. (Provérbios 13:12)",
"O que despreza a palavra perecerá, mas o que teme o mandamento será recompensado. (Provérbios 13:13)",
"A lei do sábio é fonte de vida para desviar dos laços da morte. (Provérbios 13:14)",
"O bom entendimento granjeia favor, mas o caminho dos pérfidos é penoso. (Provérbios 13:15)",
"Todo homem prudente procede com conhecimento, mas o tolo exalta a sua estultícia. (Provérbios 13:16)",
"O mensageiro perverso cai em desgraça, mas o embaixador fiel traz saúde. (Provérbios 13:17)",
"Pobreza e vergonha virão sobre aquele que rejeita a instrução, mas o que guarda a repreensão será honrado. (Provérbios 13:18)",
"O desejo que se cumpre deleita a alma; mas abominável é para os tolos apartar-se do mal. (Provérbios 13:19)",
"Anda com os sábios e serás sábio; mas o companheiro dos tolos será afligido. (Provérbios 13:20)",
"O mal persegue os pecadores, mas o bem será a recompensa dos justos. (Provérbios 13:21)",
"O homem de bem deixa herança aos filhos de seus filhos, mas a riqueza do pecador é depositada para o justo. (Provérbios 13:22)",
"Muita lavoura há na terra dos pobres, mas o que não usa de justiça, ajunta para outros. (Provérbios 13:23)",
"Aquele que poupa a sua vara aborrece a seu filho; mas o que o ama, a tempo o castiga. (Provérbios 13:24)",
"O justo come até fartar-se, mas o ventre dos ímpios passará necessidade. (Provérbios 13:25)",
"Vinde, benditos de meu Pai, possuí por herança o reino que vos está preparado desde a fundação do mundo. (Mateus 25:34)",
"Porque tive fome, e destes-me de comer; tive sede, e destes-me de beber; era forasteiro, e recolhestes-me. (Mateus 25:35)",
"Estava nu, e vestistes-me; adoeci, e visitastes-me; estive na prisão, e fostes ver-me. (Mateus 25:36)",
"Então os justos lhe responderão, dizendo: Senhor, quando te vimos com fome, e te demos de comer? ou com sede, e te demos de beber? (Mateus 25:37)",
"E quando te vimos forasteiro, e te recolhemos? ou nu, e te vestimos? (Mateus 25:38)",
"E quando te vimos enfermo, ou na prisão, e fomos visitar-te? (Mateus 25:39)",
"E, respondendo o Rei, lhes dirá: Em verdade vos digo que, quando o fizestes a um destes meus pequeninos irmãos, a mim o fizestes. (Mateus 25:40)",
"Então dirá também aos que estiverem à sua esquerda: Apartai-vos de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos. (Mateus 25:41)",
"Porque tive fome, e não me destes de comer; tive sede, e não me destes de beber. (Mateus 25:42)",
"Era forasteiro, e não me recolhestes; estava nu, e não me vestistes; e enfermo, e na prisão, e não me visitastes. (Mateus 25:43)",
"Então eles também lhe responderão, dizendo: Senhor, quando te vimos com fome, ou com sede, ou forasteiro, ou nu, ou enfermo, ou na prisão, e não te servimos? (Mateus 25:44)",
"Então lhes responderá, dizendo: Em verdade vos digo que, quando a um destes pequeninos o não fizestes, não o fizestes a mim. (Mateus 25:45)",
"E irão estes para o tormento eterno, mas os justos para a vida eterna. (Mateus 25:46)",
"Se vivemos no Espírito, andemos também no Espírito. (Gálatas 5:25)",
"Não sejamos cobiçosos de vanglórias, irritando-nos uns aos outros, invejando-nos uns aos outros. (Gálatas 5:26)",
"Suportai-vos uns aos outros, e perdoai-vos uns aos outros, se alguém tiver queixa contra outro; assim como Cristo vos perdoou, assim fazei vós também. (Colossenses 3:13)",
"E, acima de tudo, revistam-se do amor, que é o elo perfeito. (Colossenses 3:14)",
"E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos. (Colossenses 3:15)",
"A palavra de Cristo habite em vós abundantemente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros, com salmos, hinos e cânticos espirituais, cantando ao Senhor com graça em vosso coração. (Colossenses 3:16)",
"E tudo o que fizerdes por palavra ou por obra, fazei tudo em nome do Senhor Jesus, dando por ele graças a Deus Pai. (Colossenses 3:17)",
"Esposas, sede submissas a vossos maridos, como convém no Senhor. (Colossenses 3:18)",
"Maridos, amai vossas esposas, e não as trateis com amargura. (Colossenses 3:19)",
"Filhos, obedecei em tudo a vossos pais, porque isto é agradável ao Senhor. (Colossenses 3:20)",
"Pais, não irriteis vossos filhos, para que não se desanimem. (Colossenses 3:21)",
"Servos, obedecei em tudo a vossos senhores segundo a carne, não servindo só na vista, como para agradar aos homens, mas com simplicidade de coração, temendo a Deus. (Colossenses 3:22)",
"E tudo o que fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens. (Colossenses 3:23)",
"Sabendo que do Senhor recebereis o galardão da herança, porque a Cristo, o Senhor, servis. (Colossenses 3:24)",
"Mas o que faz injustiça, receberá a injustiça que fizer; e não há acepção de pessoas. (Colossenses 3:25)",
"Pois onde estiver o vosso tesouro, aí estará também o vosso coração. (Mateus 6:21)",
"Ninguém pode servir a dois senhores; porque ou há de odiar um e amar o outro, ou se dedicará a um e desprezará o outro. Não podeis servir a Deus e ao dinheiro. (Mateus 6:24)",
"Por isso vos digo: Não andeis ansiosos pela vossa vida, quanto ao que haveis de comer ou beber; nem pelo vosso corpo, quanto ao que haveis de vestir. Não é a vida mais do que o alimento, e o corpo mais do que a vestimenta? (Mateus 6:25)",
"Olhai para as aves do céu, que não semeiam, nem segam, nem ajuntam em celeiros; e vosso Pai celestial as alimenta. Não valeis vós muito mais do que elas? (Mateus 6:26)",
"E qual de vós, por mais que se preocupe, pode acrescentar um côvado à sua estatura? (Mateus 6:27)",
"E por que andais ansiosos quanto ao vestir? Considerai os lírios do campo, como eles crescem; não trabalham, nem fiam. (Mateus 6:28)",
"E eu vos digo que nem mesmo Salomão, em toda a sua glória, se vestiu como um deles. (Mateus 6:29)",
"Pois, se Deus assim veste a erva do campo, que hoje existe e amanhã é lançada no forno, não vos vestirá muito mais a vós, homens de pequena fé? (Mateus 6:30)",
"Não andeis, pois, ansiosos, dizendo: Que comeremos? ou, Que beberemos? ou, Com que nos vestiremos? (Mateus 6:31)",
"Porque todas estas coisas os gentios procuram; pois vosso Pai celestial sabe que necessitais de todas elas. (Mateus 6:32)",
"Mas buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas. (Mateus 6:33)",
"Não vos inquieteis, pois, pelo dia de amanhã, porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal. (Mateus 6:34)",
"O Senhor te guiará continuamente, e fartará a tua alma em lugares secos, e fortalecerá os teus ossos; e serás como um jardim regado, e como um manancial, cujas águas nunca faltam. (Isaías 58:11)",
"Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração. (Romanos 12:12)",
"Bendizei aos que vos perseguem; abençoai, e não amaldiçoeis. (Romanos 12:14)",
"Alegrai-vos com os que se alegram; e chorai com os que choram. (Romanos 12:15)",
"Sede unânimes entre vós; não ambicioneis coisas altas, mas acomodai-vos às humildes. Não sejais sábios em vós mesmos. (Romanos 12:16)",
"A ninguém torneis mal por mal; procurai as coisas honestas, perante todos os homens. (Romanos 12:17)",
"Se for possível, quanto estiver em vós, tende paz com todos os homens. (Romanos 12:18)",
"Não vos vingueis a vós mesmos, amados, mas dai lugar à ira; porque está escrito: Minha é a vingança; eu recompensarei, diz o Senhor. (Romanos 12:19)",
"Portanto, se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isto, amontoarás brasas de fogo sobre a sua cabeça. (Romanos 12:20)",
"Não te deixes vencer do mal, mas vence o mal com o bem. (Romanos 12:21)",
"Tudo o que fizerdes, seja em palavra ou em obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai. (Colossenses 3:17)"
];

function mostrarVersiculo() {
  const versiculoEscolhido = versiculos[Math.floor(Math.random() * versiculos.length)];

  const caixa = document.createElement("div");
  caixa.className = "versiculo";
  caixa.textContent = versiculoEscolhido;

  document.body.appendChild(caixa);
}

window.addEventListener("load", mostrarVersiculo);
let caixa;
let versiculoAtual = 0;

function criarCaixaVersiculo() {
  caixa = document.createElement("div");
  caixa.className = "versiculo";
  caixa.addEventListener("click", mostrarProximoVersiculo);
  document.body.appendChild(caixa);
  mostrarVersiculoAleatorio();
  setInterval(mostrarVersiculoAleatorio, 15000); // troca a cada 15 segundos
}

function mostrarVersiculoAleatorio() {
  versiculoAtual = Math.floor(Math.random() * versiculos.length);
  caixa.textContent = versiculos[versiculoAtual];
  caixa.style.opacity = 1;
  setTimeout(() => {
    caixa.style.opacity = 0;
  }, 12000); // desaparece após 12 segundos
}

function mostrarProximoVersiculo() {
  versiculoAtual = (versiculoAtual + 1) % versiculos.length;
  caixa.textContent = versiculos[versiculoAtual];
  caixa.style.opacity = 1;
}

window.addEventListener("load", criarCaixaVersiculo);

